### ISSUE TITLE
Error when trying to install rebound on Mac OS 12.4

### ISSUE THREAD

**Issue by zinemin** [hannorein/rebound#618] opened 2022-10-30 16:11 UTC
Hi 

I'm not very familiar with Python, trying to run REBOUND in order to evaluate a student's project using the code. 
When trying to install on Mac OS 12.4 with pycharm, I get the following error message:

Collecting rebound
  Using cached rebound-3.21.0.tar.gz (284 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rebound
  Building wheel for rebound (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/simulation.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/citations.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/horizons.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/widget.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/units.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/plotting.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/tools.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/__init__.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/interruptible_pool.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/simulationarchive.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/particle.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/data.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/rebound.h -> build/lib.macosx-10.9-universal2-3.10/rebound
      running build_ext
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DLIBREBOUND -Isrc -I/Users/simone/Downloads/rebound-main/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/binarydiff.c -o build/temp.macosx-10.9-universal2-3.10/src/binarydiff.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=44e125880e479ad32882c2a1bdfd58edc87ce3bf -DLIBREBOUND -D_GNU_SOURCE -fPIC
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
  Running setup.py install for rebound ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for rebound did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      running install
      /Users/simone/Downloads/rebound-main/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/simulation.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/citations.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/horizons.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/widget.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/units.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/plotting.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/tools.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/__init__.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/interruptible_pool.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/simulationarchive.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/particle.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/data.py -> build/lib.macosx-10.9-universal2-3.10/rebound
      copying rebound/rebound.h -> build/lib.macosx-10.9-universal2-3.10/rebound
      running build_ext
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DLIBREBOUND -Isrc -I/Users/simone/Downloads/rebound-main/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/binarydiff.c -o build/temp.macosx-10.9-universal2-3.10/src/binarydiff.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=44e125880e479ad32882c2a1bdfd58edc87ce3bf -DLIBREBOUND -D_GNU_SOURCE -fPIC
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> rebound

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

-----

I'd be very grateful for help with this issue. Thanks!

**Comment by hannorein** [comment] 2022-10-30 20:39
I suspect you might not have any compiler installed. In a terminal, try running `clang` to see if a compiler is installed 

The easiest way to get a compiler, is by downloading Xcode from the AppStore.

**Comment by hannorein** [comment] 2022-11-08 01:59
Closing this for now, but feel free to reopen if the issue is not resolved.

**Closed by hannorein** 2022-11-08 01:59 UTC
