### ISSUE TITLE
D8021 : invalid numeric argument '/Wno-unknown-pragmas' in Windows VS-Code

### ISSUE THREAD

**Issue by DarkSky7** [hannorein/rebound#692] opened 2023-06-07 00:12 UTC
I found webpages explaining that this build/install error (via 'pip install rebound') is thrown when GCC doesn't recognize a pragma, but (as you'll see in the partial build transcript below), the VisualStudio compiler is being used.  Maybe it needs a cmake tweak - what's your recommendation?  Thanks, Mike

"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DLIBREBOUND -Isrc -IC:\Programs\Python311\include -IC:\Programs\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc/binarydiff.c /Fobuild\temp.win-amd64-cpython-311\Release\src/binarydiff.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=8cfdd5ec370452803a6fc5cbf3176adca8bcfa82 -DLIBREBOUND -D_GNU_SOURCE -fPIC
      cl : Command line error D8021 : invalid numeric argument '/Wno-unknown-pragmas'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by hannorein** [comment] 2023-06-07 11:59
It looks like you're trying to use REBOUND on Windows. Have you read the note about windows here: https://rebound.readthedocs.io/en/latest/quickstart_installation/ ?

**Comment by hannorein** [comment] 2023-06-07 15:15
I'm not very familiar with windows, but it looks to me as if you're not using the Windows Subsystem for Linux (WSL).

**Comment by hannorein** [comment] 2023-06-08 14:19
I'm afraid I have no experience with Windows. But judging by the error messages and the paths that appear therein (`C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.29.3013...`) it doesn't look like you're using WSL. These paths do not exist in a unix-like environment.

**Comment by DarkSky7** [comment] 2023-06-11 02:58
So, with WSL2 installed, running: $ CC=gcc;/mnt/c/Programs/Python311/python.exe -m pip install rebound, I get the exact same result - cl.exe still does the compiling, and (naturally) it still doesn't like /Wno-unknown-pragmas

**Comment by hannorein** [comment] 2023-06-11 11:51
I don’t have access to a windows machine. But it looks to me as if you’re running the windows version of python. I found this link on how to setup the WSL version of python. https://learn.microsoft.com/en-us/windows/python/web-frameworks

**Comment by hannorein** [comment] 2023-06-11 11:52
FWIW: The pragmas are probably not the real issue. Once you fix them, you’ll get other errors about missing system calls.

**Comment by DarkSky7** [comment] 2023-06-11 12:50
Python 3.9 was installed here before WSL2 - apparently, WSL finds
PYTHONHOME and associated stuff are present and recognizes that Python is
already installed and up to date, so WSL's Python *IS* Wndows' Python. If
you think of something, I'll try it.  Figuring out which setup.py is really
doing the build might help - rebound's setup.py is not the one doing the
work.

**Comment by hannorein** [comment] 2023-06-11 14:05
I don't think you're right here. The issue is not the setup.py file - it's that you're using the windows version of python to try to compile a linux version of REBOUND. This will not work. You need to install python in WSL.

**Comment by DarkSky7** [comment] 2023-06-11 16:07
You're right.  WSL doesn't know $PYTHONHOIME.  After disabling VPN (Debian
won't install through a VPN proxy), ...

sudo apt install python3 python3-pip ipython3
/usr/bin/python3.9 -m pip install rebound
got me rebound with no complaints.

Sorry for the trouble.  I hope we're not claiming that rebound supports
windows - WSL is really a linux machine.  I'll have to see if I can get
VS-code (which I really like) to use the WSL version of python3.9

**Comment by hannorein** [comment] 2023-06-11 17:44
Glad it worked in the end. I'll close this issue now.

**Closed by hannorein** 2023-06-11 17:44 UTC
