### ISSUE TITLE
rebound vs mercury6 runtime for hybrid integrator with close encounters

### ISSUE THREAD

**Issue by ricitron** [hannorein/rebound#401] opened 2019-11-12 01:25 UTC
Hello, I've recently found rebound to run slower than expected compared to mercury6, in running tests for a project.

I am finding rebound takes ~ 5 times as long as mercury6, to integrate an identical set of embryos/planetesimals for 100,000 years, using hybrid integrators with perfect merging collisions.

This seems like too much slowdown for rebound compared to mercury6. So I am posting to ask if there is anything I am missing or any advice to speed up rebound.

I am integrating 100 embryos and 1000 planetesimals ('big' and 'small' bodies, in the mercury6 sense), plus Jupiter/Saturn, using the mercurius integrator in rebound and the hybrid integrator in mercury6. The integrators have the same timestep for the WH step (6 days), and start with identical initial conditions and the same switching radius (3 Hill radii). The min_dt value of the IAS15 integrator in rebound and the accuracy parameter of the BS2 integrator in mercury are adjusted so particles have a similar overlap during mergers (actually, with min_dt=0.005 and accuracy=1e-15, mercury6 is better resolving the mergers).

Note that I'm compiling mercury6 with 'gfortran -O3', which speeds up mercury6 by a factor of ~2.5 relative to compiling without optimization, in my testing.

I've uploaded the example test run directories [here](https://drive.google.com/drive/folders/1e5On9qy5ihCNonRb_c3jRGNzB1iDJjxx?usp=sharing).

Any advice is appreciated, thank you!

**Comment by hannorein** [comment] 2019-11-12 11:59
Hi Robert, 

In general when debugging or profiling something like this, I usually try to strip the problem down as much as possible. For example, you have quite a bit out output functionality in there which might affect the runtime a little, but more importantly make it harder for me to look at the code.

One thing you could do is set the `safe_mode` flag to 0. This should give you a significant speedup. 

Also, if I understand your code correctly, you have quite a large spread in semi-major axes. The switching radii work a little difference between the different codes. That could lead to a difference in performance but it depends a lot on the problem. You should ideally choose these parameters not to reach a good agreement between the codes, but to achieve some convergence of the quantities which you are actually interested.

**Comment by hannorein** [comment] 2019-11-12 15:59
I ran a few short tests with your code. Initially, it took 7s to run. After removing the output functions, it was down to 5s. Setting the safe_mode flag to 0 further reduced it to 4s. 

I'll have a look if I find anything else which is slowing you down. But this probably getting you already closer to the speed you measured for Mercury.

**Comment by hannorein** [comment] 2019-11-12 16:50
For your specific setup (`testparticle_type=1`, `N=1100`, `N_active=100`), there is a way to accelerate the gravity calculation (basically going from O(N^2) to O(0.5*N^2)). I've played around a bit and the best I could come up with is another ~25% improvement, reducing the time in the test problem to about 3.4s (less than half of where we started). I've pushed it to the fastgravity branch. If you use this, please run some tests with the original gravity routine, just to make sure the new one is giving similar results.

**Comment by ricitron** [comment] 2019-11-14 01:25
Thanks a ton for looking into this, Hanno. 

Is the speedup you report just for the first timestep? My output is only every 10,000 yr, so it shouldn't cause much slowdown over the 100,000 yr test simulation. 

My original test takes 15.6h to run 100,000 yrs. Removing the output results in no runtime difference. If I run with WHFAST and no collisions, it takes 3.25h, so most of the work is going on in the close encounters / ias15 integrator. For this reason, running in unsafe mode doesn't significantly improve the runtime (actually I noticed the runtime increase to 16.2h in one test, with unsafe mode, for some reason). 

I tested with the fastgravity branch but the runtime only improved to 15h. 

In mercury, the simulation takes 3.23h when compiled with 'gfortran -O3' (or 2.56h when compiled with ifort -O3). The main parameter I'm interested in is resolving the mergers (similar number of collisions and similar overlap between particles at moment of collision). With the parameters I used, mercury and rebound achieve similar number of collisions but mercury has less overlap at the time of impact. 

What is the issue with my initial spread of semi-major axes? I'm using initial conditions common to simulating this type of planetary accretion problem. In what ways could I modify the switching radii or other rebound parameters to speed up the simulation but achieve a similar result?

**Comment by hannorein** [comment] 2019-11-14 13:27
I ran it for a few thousand years not just one timestep. Some general advice when you're debugging/profiling code: try to come up with tests that don't require you to wait 16 hours to find out if a change is faster or slower. That makes profiling much easier!

The critical distances are calculated here: https://github.com/hannorein/rebound/blob/master/src/integrator_mercurius.c#L407. Those are slightly different to the way Mercury handles it. If the critical distances calculated here are much larger than in Mercury, then you end up with a lot of particles undergoing an encounter at any given time. 

I'm happy to try again to speed it up if you can give me a short example that runs in a couple of seconds.

**Comment by ricitron** [comment] 2019-11-15 05:59
Thanks for the feedback! I uploaded a shorter example [here](https://drive.google.com/drive/folders/1fPmLAfGOCs3XTA7yIYf6pFuvnsE4UMz7?usp=sharing). I wanted to test the behavior when the disk was stirred up a bit and collisions were occurring, so I begin with the particles at their positions a couple timesteps prior to the first collision (as recorded in the initial rebound simulation). I tested running for 50 and 500 yrs (note that in rebound I define G so it is using mercury6 units). 

Running for 50 years, mercury6 takes 5.95s. Rebound takes 28.05s. With fast_gravity, rebound takes 26.33s, and with fast_gravity plus unsafe_mode it takes 26.19s. Note however that in these 50 years rebound records a collision but mercury6 does not record a collision.

I ran again for 500 yrs, so that rebound and mercury both record a collision (although the collision occurs between different bodies, depending on the code). Over 500yrs, mercury takes 54.68s, and rebound takes 4m49.60s at default behavior or 4m22.12s with fast_gravity and unsafe_mode. Note that I'm compiling mercury with 'gfortran -O3'. 

I checked the collision diagnostics I output and find the timestep at the moment of collision in mercury is 0.00082 days, smaller than the minimum timestep I set for rebound (0.005 days). Also, the collision is better resolved in mercury (less overlap between colliding bodies).

**Comment by ricitron** [comment] 2019-11-15 06:07
I did a couple more tests and diagnostics.

First, I examined the number of big/small particles integrated during close encounters. In mercury, I was getting 20-30 'big' particles and 40-60 total particles integrated in the BS step. This was larger than the number integrated in the IAS15 step of rebound, where I was finding values of encounterNactive=10-20 and encounterN=30-40. 

Second, I also looked at the dcrit values. For mercury, the dcrit value was ~ 0.058 a.u. for all particles, and was set by the velocity condition, with the exception of Jupiter/Saturn, where the dcrit value was a bit over 1 a.u. and was set by the hill radius condition). For rebound, the dcrit values were generally equal to or less than those from mercury. 

Third, I tried examining the behavior of the IAS15 vs BS and WHFAST vs MVS integrators separately. With the same initial particle positions as the previous test, I integrated all N=100,n=1000 particles with mercury's BS integrator for 1 year, which took 6.074s. In rebound, this took 9.361s with IAS15. I then integrated the same N=100 big particles, but without small particles (because MVS doesn't allow small particles), for 1000 yrs. In mercury with MVS this took 5.555s, and in rebound with WHFAST this took 7.874s. 

While the WHFAST and IAS15 performed a bit longer than mercury, it was not near the ~5x slowdown I was finding when using MERCURIUS (compared to mercury's hybrid scheme). Given the dcrit values are similar, and mercurius has less particles per encounter, I'm still confused on the slowdown I'm observing.

**Comment by hannorein** [comment] 2019-11-19 17:23
Hi Robert, 

Thanks a lot for the follow-up. This should make it much easier for me to look into. My computer broke down and is currently being repaired. I'm using and old computer as a backup, so it might take me a little longer...

Hanno

**Comment by hannorein** [comment] 2019-11-20 15:21
I'm a bit puzzled as to what is going on here. When I profile the REBOUND simulation, I can see that a comparable amount of time is spent in the WHFast and IAS15 parts of the code. That means speeding up either of the two parts is not really going to help much. But given that each part individually is not 5x slower than the Mercury equivalent, I don't understand how the combination can be so much slower. I'll keep playing around with it...

**Comment by Cosmicstring** [comment] 2020-09-01 12:07
Is there any further insight on this?

**Comment by hannorein** [comment] 2020-09-03 12:06
I'm afraid no. I'm working on a replacement hybrid integrator, which is close to being ready. But I don't want to promise a date when it'll be out yet.

**Comment by Cosmicstring** [comment] 2020-09-03 19:55
Alright, thank you for the update!

**Comment by hannorein** [comment] 2021-01-06 17:56
I know it's been a while but I'm looking into this once again...

**Comment by dmhernan** [comment] 2021-02-03 15:53
Hi all, I thought I'd mention I also received a report of this issue since 2019 and I've been very concerned.  Do we have any ideas on what's going on?  I'm also interested in solving this, but maybe a solution is already near.

**Comment by hannorein** [comment] 2021-02-12 02:26
I just pushed a small update (see above) which rearranges the gravity for loop for non OPENMP runs. For very small numbers of particles, this might be slower. But for larger numbers of particles this should bring the runtime from O(N^2) to O(0.5*N^2). This change, together with the `safe_mode` flag brings the speed from 5x mercury down to 3x mercury for this specific example. I don't think the change should have any adverse effects so I'll merge it into the master branch shortly.

Other than that, I don't see any obvious issues. There are several differences between the codes, so I'm not surprised to see a difference in runtime. I think with the recent changes, the integrator provides a reasonable balance between being fast and general at the same time. In the end, it's a hybrid integrator and there are all kind of compromises to make. So I'll close this issue for now, and it's always possible to get a speedup for specific cases.

@gekaremi, @Cosmicstring and @annacrnn, if you have a specific use case in mind, send me an e-mail with a short example and I'd be happy to see if we can speed it up any further together.

A few general comments in case someone finds this post later: 
- The switchover criteria in MERCURIUS is different from the one in mercury. If one removes all the criteria except the hill radius (see [this line](https://github.com/hannorein/rebound/blob/main/src/integrator_mercurius.c#L373)), then I get a speed of ~2x mercury. For some specific use cases, it might be ok to play around with these criteria.
- IAS15 uses one timestep for all the particles which have a close encounter. Thus if there are many simultaneous close encounters, the timestep will be limited by the closest encounter. Depending on the use case, this can be a significant bottleneck. Increasing the physical size of objects could be one solution if this can be justified. I'm hesitant to change this behaviour in general. I think it's a feature, not a bug. One can come up with scenarios where a particle having a very close encounter can influence all other particle on a very short timescale. 
- A special use case might be the one related to what @katvolk mentioned in #494, where test particles have close encounters but never have any influence on another particles. There, one might want to run something like one IAS15 integration per particle, thus avoiding the issue of having the same timestep for all particles. If anyone thinks they need something like this, send me an e-mail and I'll see how difficult it would be to implement.

**Closed by hannorein** 2021-02-12 02:26 UTC
Labels: urgent
