### ISSUE TITLE
Problem with Bouncing String Example in Updated Version

### ISSUE THREAD

**Issue by sjarmak** [hannorein/rebound#323] opened 2018-02-16 16:49 UTC
When I run the bouncing_string example in an older version of REBOUND there are no apparent issues and the spheres continuously run into each other along the same axis. However, when I run this same example using the most recent version of REBOUND, after a certain period of time (t ~ 6, fairly quickly), the particles begin to go off axis and start moving around arbitrarily and blinking in and out of existence. What is going wrong here, is it something wrong with the reb_collision_resolve_hardsphere method?

Edit: I realized that in the old version of REBOUND I had changed the coefficient of restitution to 0.8, when I change this back to a value of 1 (perfect bouncing) the problem of the system going crazy occurs, and when I add in a coefficient of restitution < 1 to the updated collision.c code it doesn't appear to have this problem anymore. I am at a loss though for the requirement of a coefficient of restitution < 1.

**Comment by hannorein** [comment] 2018-02-16 21:49
I think what you're seeing makes sense. There is no dissipation when using a coefficient of restitution is 1, so they should keep bouncing forever. But because there are small numerical errors (even if they are as small as 1e-16 initially), eventually the system will go unstable. In any real physical system there should be some damping. That makes everything more stable. You might be able to delay the instability by choosing a smaller timestep.

**Comment by sjarmak** [comment] 2018-02-17 02:15
Hm, I'm just concerned that it would break apart so fast, and always at approximately the same time. I ran the program again with dt = 1e-6 instead of 1e-3 and it broke at t = ~6 seconds. Is this something that is expected?

**Comment by hannorein** [comment] 2018-02-17 02:18
It's an unstable equilibrium. So I'm not too surprised. In the real world, try making two basketballs bounce on top of each other more than once.

**Comment by hannorein** [comment] 2018-02-17 02:28
(I just run the example myself.)

Yes, I think this is the expected behaviour. Small errors amplify and after a few periods, they will reach order unity. What you describe as "blinking in and out" is also expected. The example uses three root boxes in one dimension and one it the other two. The visualization should probably highly those root boxes better to avoid any confusion. (See Rein & Liu for more).

I'll close this for now as I think everything is ok, but feel free to reopen if anything is unclear you you think there is a problem.

**Closed by hannorein** 2018-02-17 02:28 UTC
