### ISSUE TITLE
Calculting impact velocity distributions using MERCURIUS integrator 

### ISSUE THREAD

**Issue by richard17a** [hannorein/rebound#669] opened 2023-03-13 13:20 UTC
Hi all,

Hopefully this is a quick question -  I am using REBOUND to generate the impact velocity distribution of test-particles onto an Earth-like planet, and I am using the MERCURIUS integrator (and the default direct collision detection module). My understanding is that when this switches over to the IAS15 integrator, it should accurately resolve close encounters and collisions, as it adaptively changes its timestep. 

I have attached an example distribution below - and my question is regarding the small fraction of the impacts below the planet's escape velocity (black dotted line), which shouldn't really be possible. I am currently switching to the IAS15 integrator at 5Rhill - do you think that if I increased this value, or just used the IAS15 integrator throughout, this would prevent these low velocities? (A rough calculation suggests that if the planet is not completely picked up by WHFast, this could possibly explain these lower velocities - but it would be great to get your opinions on this in case anything else is at play).

Thanks very much, 
Richard

[impact_velocity_distribution.pdf](https://github.com/hannorein/rebound/files/10957432/github_issue_fig.pdf)

**Comment by hannorein** [comment] 2023-03-13 13:27
Hi Richard, 

Are you sure the velocities are actually below the escape velocity? It looks like the centre of the bin is actually above the line.

In any case, I would not be surprised if you see a few impact just below the escape velocity. Keep in mind that this is a three body system, so the energy of your impactors is not perfectly conserved. Running a few tests with a different integrator or a larger switching radius are a good idea to confirm that it's not a numerical issue. 

Hanno

**Comment by richard17a** [comment] 2023-03-13 13:51
Hi Hanno,

Thanks very much for the quick reply! The minimum velocity is 10.98 km/s (compared to the escape velocity ~11.2 km/s - so it's not just a binning artefact or anything like that. You are right that these low velocities might not quite as strange as I initially thought, but will make sure to run some tests to make sure it isn't a numerical effect.

Thanks again, 
Richard

**Comment by hannorein** [comment] 2023-03-13 14:16
It can of course be a bug or a numerical issued, but I think it's perfectly reasonable to expect this kind of velocity due to three body dynamics. So I wouldn't be worried. But if you want to make sure, you could do the following test (I assume these are small test particles?): Make the simulations reproducible, but finding out which particle will be the one with the low velocity, restart the simulation with just this one test particle (+ planet + star), then play around with different integrators, timesteps, etc. Start 1/4 orbit before the encounter, so your results are not affected by chaos in the system.

**Comment by hannorein** [comment] 2023-09-25 14:29
I'll close this issue for now but feel free to reopen if there still is a problem.

**Closed by hannorein** 2023-09-25 14:29 UTC
