### ISSUE TITLE
OpenMP changes from 3.10.0 and 3.12.1

### ISSUE THREAD

**Issue by zdrc** [hannorein/rebound#422] opened 2020-04-06 17:36 UTC
I believe I've discovered some OpenMP parallelization problems in the newest version(s). I've attached my Makefile and simulation file below.

I recently upgraded from 3.8.2 to 3.12.1 and I no longer get a speedup with OpenMP. It seems like this change happened sometime between 3.10.0 and 3.12.1

For version 3.12.1, with anything more than one core, the simulation grinds to halt, and is unable to integrate the system at all. In version 3.12.1, the sim outputs about once every ~40 seconds of walltime with one core, and with 4 cores this walltime becomes infinite (I can't get the sim to integrate for even one orbit).  In version 3.10.0, the sim outputs about once every ~40 seconds of walltime with one thread, and with 4 threads this walltime becomes ~20 seconds. The only thing that changes is which git commit I'm checking out. Any ideas what this might be?

Makefile
```
ifneq (,$(findstring shas,$(shell hostname)))
	REB=$(PROJ)/new-rebound/src
	export OPENGL=0
	export OPENMP=1
else
	REB=$(HOME)/work/rebound/src
	export CC=gcc-9
	export OPENMP=1
endif
include $(REB)/Makefile.defs

all: librebound
	@echo ""
	@echo "Compiling problem file ..."
	$(CC) -I$(REB) -Wl,-rpath,./ $(OPT) $(PREDEF) sim.c -L. -lrebound $(LIB) -o rebound
	@echo ""
	@echo "REBOUND compiled successfully."

librebound: 
	@echo "Compiling shared library librebound.so ..."
	$(MAKE) -C $(REB)
	@-rm -f librebound.so
	@cp $(REB)/librebound.so .
#	@ln -s $(REB)/librebound.so .

clean:
	@echo "Cleaning up shared library librebound.so ..."
	@-rm -f librebound.so
	$(MAKE) -C $(REB) clean
	@echo "Cleaning up local directory ..."
	@-rm -vf rebound
```

The sim.c file (note that I initialize the system with a python script that generates a simulation archive that is then loaded by the c program)
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <math.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <omp.h>
#include "rebound.h"


void heartbeat(struct reb_simulation* r);
double tmax;

int orbits;
double orbit_time;
float num_saves_per_orbit;

char tfilename[100] = "comp_time.csv";
char safilename[100] = "sa-archive.bin";
clock_t last_hb;

int main(int argc, char* argv[]){
    /////////////////////////////////////////////////////////////////////////
    // Load the sim from the created archive
    struct reb_simulation* r = reb_create_simulation_from_binary("initial-conditions.bin");
    /////////////////////////////////////////////////////////////////////////
    // Set up constants and pointers
    r->integrator = REB_INTEGRATOR_IAS15;
    r->heartbeat = heartbeat;
    r->G = 1;
    r->ri_ias15.min_dt = 1e-7;
    /////////////////////////////////////////////////////////////////////////
    // Move to center of mass frame
	reb_move_to_com(r);
    /////////////////////////////////////////////////////////////////////////
    // Set tmax
    orbits = 1e4;
    orbit_time = 2*M_PI;
    num_saves_per_orbit = 1.;
    tmax = orbits * orbit_time;
    /////////////////////////////////////////////////////////////////////////
    // Get the save file location
    // TODO clean this shit up
    if (argc > 1) {
        for (int i=1; i < argc; i++) {
            if ( !strcmp(argv[i], "save_loc") ) {
                i++;
                memset(tfilename, 0, 100);
                memset(safilename, 0, 100);
                sprintf(tfilename, "%s%s", argv[i], "comp-time.csv");
                sprintf(safilename, "%s%s", argv[i], "sa-archive.bin");
            }   
        }
    }
    /////////////////////////////////////////////////////////////////////////
    // Set up simulation archive saving
    reb_simulationarchive_automate_interval(r, safilename, orbit_time/num_saves_per_orbit);
    /////////////////////////////////////////////////////////////////////////
    // Begin integration
    last_hb = clock();
    reb_integrate(r, tmax);	
    /////////////////////////////////////////////////////////////////////////
    // free up memory?
    reb_free_simulation(r);
    printf("\n");
}    

void heartbeat(struct reb_simulation* r) {
    if (reb_output_check(r, orbit_time/num_saves_per_orbit)) {
        /////////////////////////////////////////////////////////////////////
        // Output progress to screen
        reb_output_timing(r, tmax);
        /////////////////////////////////////////////////////////////////////
        // Record the time between heartbeats in milliseconds
        int threads = omp_get_max_threads();
        int msec_since_last_hb = (clock() - last_hb)*1000/(CLOCKS_PER_SEC*threads);
        last_hb = clock();
        FILE* tf = fopen(tfilename, "a");
        fprintf(tf, "%d,%e\n", msec_since_last_hb, r->t/orbit_time);
        fclose(tf);
        /////////////////////////////////////////////////////////////////////
    }
}
```

**Comment by hannorein** [comment] 2020-04-06 17:52
Hi Alex (?), 

Thanks for pointing this out. It's not unlikely that there is an issue with the OpenMP part. I have not used this part myself for quite some time now, but changed various other things which could have impacted OpenMP.

Is there any chance you can provide a short self-contained snipped of code which reproduces the issue? Because you initialize the system from a binary file, I don't really know what kind of system you're interested in (how many particles, what type of particles, etc). 

Also, is there any chance you have to two commit hashes which you're referring to? Just to make sure we're talking about the same.

Cheers,
Hanno

**Comment by hannorein** [comment] 2020-04-06 21:08
The commit you quoted is the current one. Did you mean to copy and paste a different one?

**Comment by zdrc** [comment] 2020-04-06 21:15
Whoops! I  meant cf6e6ff327f4c7c8875917f5449705fadc38e7a2. I double checked to make sure that I was actually checking out the right commits earlier.

**Comment by hannorein** [comment] 2020-04-06 21:17
Thanks. That'll help me narrowing the problem down. It looks like ias15 did not change, so it must be an issue in the gravity routine... looking into it...

**Comment by hannorein** [comment] 2020-04-07 21:00
So I think this is due to a refactoring of the gravity routine. In the old version the loop was O(N^2). In the new version, it was O(1/2 * N^2) which is faster on a single CPU. The problem is that  memory access is now more random and this prevents any efficient use of OPENMP. I now simply switch back to the old gravity routine back whenever OPENMP is used. It's currently on the `openmpfix` branch. Could you check if this speeds up your code on your machine?

Thanks!

**Comment by zdrc** [comment] 2020-04-07 21:26
This fix worked. The code is now running normally in parallel on my machine. Thanks for the fix!

**Comment by hannorein** [comment] 2020-04-07 21:45
Excellent! Thanks for reporting the issue. I thought the original change made the code faster but it did the opposite in your case. I'll merge it into the master branch and close this issue.

**Closed** 2020-04-07 21:46 UTC
