### ISSUE TITLE
Simulation returning NaNs after a certain timestep

### ISSUE THREAD

**Issue by Spiruel** [hannorein/rebound#321] opened 2018-02-02 22:08 UTC
I am running a Solar System back in time, with lots of random test particles. Around t = -99000 all particles disappear and the output is all NaNs - but the simulator keeps integrating. I'm assuming the problem is similar [to this](https://github.com/hannorein/rebound/issues/303), but I can't work out the problem. 

Is it possible to find out what's causing the simulation to break at this timestep every time, and what steps can be taken to ensure this doesn't happen? Thanks.

I've attached an example bin file in order to reproduce the effects.
[test.tar.gz](https://github.com/hannorein/rebound/files/1690994/test.tar.gz)

**Comment by hannorein** [comment] 2018-02-04 16:11
Could you also post the code that you used? It helps if you can strip it down to the bare minimum that reproduces the issue. Thanks!

**Comment by Spiruel** [comment] 2018-02-04 21:13
Sure, here's a MWE:

```
import numpy as np
import rebound

sim = rebound.Simulation()
sim.integrator = "mercurius"
solar_system_objects = ["Sun", "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
sim.add(solar_system_objects, date="2017-12-01 12:00")
sim.N_active = 9
sim.testparticle_type = 1
sim.move_to_com()
sim.status()

sim.dt = -0.1
earth = sim.particles[3]

# velocities in AU/yr/2pi
year = 2.*np.pi # One year in units where G=1
AU_m = 149597870700 # One AU in metres
R = 4E8/AU_m #4e8 metres in AU for radius of EMS
AU_yr = 4740.57172*year
vel_conv = AU_m*2.*np.pi/(365*24*60*60) # unit of velocity in m/s  #DIVIDE BY THIS TO GET INTO SIM UNITS
#G=1, unit of length = 1AU, unit of time = year/(2pi)

for i in range(100):
    out_of_ems = False # if resultant velocity falling inside ems, get new velocity

    while not out_of_ems:
        theta = np.arccos(2*np.random.random() - 1)
        phi = np.random.random() * 2 * np.pi
        x = R * np.sin(theta) * np.cos(phi)
        y = R * np.sin(theta) * np.sin(phi)
        z = R * np.cos(theta)

        dir_vec = np.array([x,y,z])
        max_vel_pass = False # if length larger than the 72 km/s stipulated as a maximum, sample rejected and new vel chosen
        while not max_vel_pass:
            rand = np.random.randint(20E3,40E3)
            vx, vy, vz = rand * (dir_vec/np.sqrt(dir_vec.dot(dir_vec)))

            res_x, res_y, res_z = earth.x+x, earth.y+y, earth.z+z #resultant displac/velvectors once radial vev added to ems
            res_vx, res_vy, res_vz = earth.vx + vx, earth.vy + vy, earth.vz + vz

            if np.sqrt((res_vx)**2 + (res_vy)**2 + (res_vz)**2) < (72E3):
                max_vel_pass = True
            else:
                print 'max vel exceeded'

        if np.sqrt((res_x*AU_m)**2 + (res_y*AU_m)**2 + (res_z*AU_m)**2) - np.sqrt((res_x*AU_m+res_vx)**2 + (res_y*AU_m+res_vy)**2 + (res_z*AU_m+res_vz)**2) < 0:
            out_of_ems = True
    #print np.sqrt(res_vx**2 + res_vy**2 + res_vz**2)

    sim.add(m=0,x=earth.x+x, y=earth.y+y, z=earth.z+z, vx=res_vx/vel_conv, vy=res_vy/vel_conv, vz=res_vz/vel_conv)

Noutputs = 10000
t_end = 100000
print 'Integrating to', -t_end, 'yrs (' + str(t_end*year) +')'
times = np.linspace(0.,-t_end*year, Noutputs)
part_num = sim.N

ps = sim.particles 
for i,time in enumerate(times):
    sim.integrate(time, exact_finish_time=0)
    print ps[0].x
```

The simulation will begin to fail around time=-98781.551184

**Comment by hannorein** [comment] 2018-02-04 22:56
Thanks. I can reproduce your issue. If one particle's position becomes NaN, then this will propagate to all other particles within 1 timestep. So this is likely just caused by one particle. Clearly this should not happen, but I'll need to investigate. Interestingly, saving the simulation just before this happens, then restarting, resolves the issue (I'd rather have the issue still be there, that would be easier to debug)... I'll look into it and let you know what I find!

**Comment by hannorein** [comment] 2018-02-05 00:41
I'm seeing a python doc string in my binary files. This looks more and more like a memory issue.

**Comment by hannorein** [comment] 2018-02-05 01:06
Strangely, even this example generates different binary files.

```
sim = rebound.Simulation()
sim.add(m=1)
sim.save("out1.bin")
sim = rebound.Simulation.from_file("out1.bin")
sim.save("out2.bin")
```

**Comment by hannorein** [comment] 2018-02-05 20:36
So I think I nailed down the root cause of this. It's deep inside the WHFast Kepler solver. It has an issue with very eccentric or hyperbolic orbits and negative timesteps. That's because were using floor(dt*...) at some point. Thinking about a way to fix it!

**Comment by hannorein** [comment] 2018-02-06 15:48
So I think the above patch solves the problem. At least your test case works now. I'll write a unit test to be absolutely sure...

**Comment by Spiruel** [comment] 2018-02-06 16:36
My code seems to be functioning as intended now with the latest update of Rebound. Many thanks for your work to fix this.

**Comment by hannorein** [comment] 2018-02-06 16:37
Thanks for posting a bug report!

**Comment by Spiruel** [comment] 2018-02-06 18:59
Unfortunately another issue has appeared. I don't know if it's related, but when using the example code above, the aphelia of all the orbits seems to rapidly and unnaturally grow around the -125000 mark.

**Comment by hannorein** [comment] 2018-02-07 02:10
You're right. I think I know what going on...

Short solution is to just reverse the velocities of every particle and then integrate forward in time.

**Comment by Spiruel** [comment] 2018-02-07 13:27
Of course - I'll use that approach. Again, many thanks for your help with this.

**Comment by hannorein** [comment] 2018-02-07 13:54
You might also want to double check your initial conditions. I'm not totally sure what you want to setup, but it looks like there might be something wrong (in particular, check the units).

**Comment by hannorein** [comment] 2018-02-07 17:03
I've coded up a simple hack that just flips the sign of the velocities and the timestep inside the Kepler step to ensure it always works. I think this is probably the best solution, but I'd love to hear what @dtamayo thinks. Commits are currently on branch newbacktime.

**Comment by hannorein** [comment] 2018-02-25 19:57
I'll close this issue for now. The recommended solution is to choose a time variable that monotonically increases during a simulation. This does not limit the kind of simulation and one can still integrate backwards in time by simply flipping the sign of the velocities. 

I will try to work on a proper fix in the future, but for now, there are just too many places in the code where the sign of the timestep matters.

**Closed by hannorein** 2018-02-25 19:57 UTC
Labels: bug

**Comment by PauloDoMonte** [comment] 2022-03-09 06:32
I'm having the same problem in my code, has this bug been fixed?

**Comment by hannorein** [comment] 2022-03-09 19:10
It would help if you can post a simple example that reprocess the issue. Are you integrating backwards in time like the OP?

**Comment by PauloDoMonte** [comment] 2022-03-13 02:28
I'm not integrating backwards in time.
This is my code:

================================== CODE ======================================
import rebound

sim = rebound.Simulation()
sim.units = ("kg","km","s")
sim.integrator = "IAS15"

sim.add(m=1.989e+30,r=69634) #SUN
sim.add(m=5.973332e+24,r=6378.1366,x=-1.453091711410064E+08,y=3.065055370063527E+07,z=-7.925042448136955E+02,vx=-6.623093040898302E+00,vy=-2.926662424847545E+01,vz=4.500915920360171E-04) #EARTH
sim.add(m=7.349e+22,r=1737.4,x=-1.453091711410064E+08,y=3.065055370063527E+07,z=-7.925042448136955E+02,vx=-6.623093040898302E+00,vy=-2.926662424847545E+01,vz=4.500915920360171E-04) #MOON

print(sim.particles[0])
print(sim.particles[1])
print(sim.particles[2])

sim.integrate(10)

print(sim.particles[0])
print(sim.particles[1])
print(sim.particles[2])
================================== CODE ======================================

This is the program's output
================================== OUTPUT ======================================
<rebound.particle.Particle object at 0x7f172108ba40, m=1.989e+30 x=0.0 y=0.0 z=0.0 vx=0.0 vy=0.0 vz=0.0>
<rebound.particle.Particle object at 0x7f172108ba40, m=5.973332e+24 x=-145309171.1410064 y=30650553.70063527 z=-792.5042448136955 vx=-6.623093040898302 vy=-29.26662424847545 vz=0.0004500915920360171>
<rebound.particle.Particle object at 0x7f172108ba40, m=7.349e+22 x=-145309171.1410064 y=30650553.70063527 z=-792.5042448136955 vx=-6.623093040898302 vy=-29.26662424847545 vz=0.0004500915920360171>
<rebound.particle.Particle object at 0x7f172108ba40, m=1.989e+30 x=nan y=nan z=nan vx=nan vy=nan vz=nan>
<rebound.particle.Particle object at 0x7f172108ba40, m=5.973332e+24 x=nan y=nan z=nan vx=nan vy=nan vz=nan>
<rebound.particle.Particle object at 0x7f172108ba40, m=7.349e+22 x=nan y=nan z=nan vx=nan vy=nan vz=nan>

**Comment by Findus23** [comment] 2022-03-13 08:17
That seems like the correct output. The moon is in the exact same position as your Earth and therefore the gravitational force between them is infinite.

**Comment by hannorein** [comment] 2022-03-13 13:32
👆That's the right answer.
