### ISSUE TITLE
conda forge ARM-64 version  of rebound for mac OS

### ISSUE THREAD

**Issue by mschwamb** [hannorein/rebound#716] opened 2023-08-23 17:49 UTC
I'm trying to install rebound on my M2 mac. I'm finding there's an ARM-64 version of rebound on pypy but not a conda-forge version. Is it possible to push a ARM-64 version  of rebound for mac OS onto conda-forge? Thanks!

**Comment by hannorein** [comment] 2023-08-23 17:52
I'm not a condo person so I don't know what this involves... Does pip not work with conda?

**Comment by hannorein** [comment] 2023-08-23 17:53
(I'm not sure why you think there is an ARM-64 version of rebound on pypy. It should only be a source distribution.)

**Comment by Francyrad** [comment] 2023-08-23 19:09
With pip install works fine

**Comment by hannorein** [comment] 2023-08-23 19:16
Thanks. Glad to hear it works with pip. Someone needs to explain conda to me at some point. I'm always so confused!

**Comment by mjuric** [comment] 2023-08-23 22:53
Hi all -- I've got a [PR](https://github.com/conda-forge/rebound-feedstock/pull/80) on the conda-forge feedstock that should flip the right switches to enable their machinery to build a native Apple Silicon binary. Looks like the tests pass, take a look when you get a chance.

(n.b., after this is merged it'd be fun to do a performance comparison of emulated vs. native Apple builds).

**Comment by hannorein** [comment] 2023-08-24 18:37
Thank you! I've merged the PR. @mschwamb, let us know if it works!

**Comment by pearsonkyle** [comment] 2023-09-13 23:00
@hannorein 

I can confirm that the installation on conda forge works using: `conda install -c conda-forge rebound` 

where as the pip install still did not work on a mac M2 Pro

**Comment by mjuric** [comment] 2023-09-13 23:04
Just to confirm I only fixed the conda packaging (this specific issue); don't have as much experience with pypi/wheels, I'm afraid.

**Closed** 2023-09-19 13:04 UTC
