### ISSUE TITLE
CR3BP - Plot Poincaré Map - Theory/REBOUND Questions

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#433] opened 2020-04-24 21:30 UTC
Hello,

About a while ago I am trying to use REBOUND to build sections of Poincaré.

My questions are:

1) When adding a particle using Cartesian coordinates, are these coordinates in the Barycentric / Heliocentric framework?

2) When using the sim.move_to_com () command does it move to the Barycentric referential? If I remove the orbital elements as eccentricity, after inserting the command sim.move_to_com () will they be jacobi coordinates?

I'm trying to plot the section for regular orbits and I'm having difficulties. Am I forgetting something?

Gabriel Caritá

[CODE](https://github.com/gabiruzo/CR3BP/blob/master/POINCARE-MAP-REBOUND.ipynb)

**Comment by hannorein** [comment] 2020-04-24 21:39
Hi Gabriel, 

REBOUND internally always uses an inertial frame. When using cartesian coordinates, the particles are simply added in the simulation's inertial frame. (the meaning of the inertial frame depends on how you set it up)

When you use orbital elements, then particles are added using Jacobi coordinates by default. But you can also specify the primary object. This could be the central object (thus you're using heliocentric coordinates), or the barycentre (thus you're using barycentric coordinates). 

When you use `move_to_com()`, then all particles are moved to the barycentric frame (also an inertial frame). 

I'd suggest you just play around a little with adding particles in different ways, then print out the xyz positions of particles. 

I hope this helps.
 Hanno

**Comment by gabiruzo** [comment] 2020-04-24 21:48
Hello Hanno,

I tried to share my code but I'm new in the GitHub. I just share the link.
I read in API about to use `calculate_com()` to get barycentric positions. Apparently it made no difference when I use `move_to_com()` at start.
I can plot the graphs of the positions and also those of the zero speed curves. I'm probably missing something on the functions to plot poincare map.

Gabriel

**Comment by hannorein** [comment] 2020-04-24 21:53
`move_to_com()` moves particles. You need to add particles first for it to have any function.

**Comment by hannorein** [comment] 2020-04-24 21:57
Hi Gabriel, 

I'm not sure what the problem is, but I think you're way overthinking the issue of the centre of mass coordinates. The two functions do exactly what they say they do:

`calculate_com()` This function calculates the coordinates of the centre of mass and returns it.

`move_to_com()` This function moves the function to the centre of mass frame. After you call this function, `calculate_com()` will always return 0. 

Hanno

**Comment by gabiruzo** [comment] 2020-04-24 22:06
I'm sorry for the confused question. You answered what was worrying me

Gabriel.

**Comment by hannorein** [comment] 2020-04-24 22:07
No worries. All these coordinates can be quite confusing. I'll close this issue for now, but feel free to open it again if you have more questions. 
  Hanno

**Closed by hannorein** 2020-04-24 22:07 UTC

**Comment by gabiruzo** [comment] 2020-09-07 12:59
Hello.

Problem solved.

For future references, some changes to the Jacobi integral were necessary due to the Jacobi coordinates used by REBOUND.

In this link: `http://assets.press.princeton.edu/chapters/s7687.pdf` a detailed description of the CR3BP planar problem in jacobi coordinates is discussed.

After changes on relative separations the Jacobi constant is being kept until the 15th place after the comma.

Thanks for the help @dtamayo and @hannorein

**Comment by hannorein** [comment] 2020-09-07 13:07
Fantastic!
