### ISSUE TITLE
GLSL 3.30 not supported, examples core dump

### ISSUE THREAD

**Issue by perrinmeyer** [hannorein/rebound#284] opened 2017-06-26 17:26 UTC
On Ubuntu 16/04,

>> sudo apt install libglfw3
installs GLSL 3.3

when compiling in shearing_sheet
>> make 
>> ./rebound

results in
REBOUND compiled successfully.
perrin@perrin:~/rebound/examples/shearing_sheet$ ./rebound 
Toomre wavelength: 61.009899
N_tot=  1536      t=  0.011000 [orb]  dt=  47.804408  cpu=  0.019966 [s]  

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile vertex shader.

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile vertex shader.

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile vertex shader.

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile vertex shader.

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile vertex shader.
Segmentation fault (core dumped)

**Comment by hannorein** [comment] 2017-06-26 17:30
Can you check if your graphic card and driver support OpenGL Shader Language (GLSL) version 3.30.

**Comment by perrinmeyer** [comment] 2017-06-26 17:36
can you perhaps tell me the magic incantation on ubuntu that would tell me this? 

currently I'm at a remote office with a (super cute)  Intel NUC with and i7 w integrated intel graphics, and I have not used this for anything real yet.  (at my main office  I have a 4way amd w NVIDIA card, but I wont have a chance to try that today)

thanks

**Comment by perrinmeyer** [comment] 2017-06-26 17:40
does this help (from askubuntu)

perrin@perrin:~$ glxinfo | grep -i "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 12.0.6
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
perrin@perrin:~$

**Comment by perrinmeyer** [comment] 2017-06-26 17:40
(I have no idea why everything is strikethrough. weird...)

**Comment by perrinmeyer** [comment] 2017-06-26 17:41
perrin@perrin:~$ glxinfo | grep -i "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 12.0.6
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
perrin@perrin:~$

**Comment by rieder** [comment] 2017-06-27 04:06
(Strikethrough is caused by tilde: `~like this~` -> ~like this~.)

**Comment by perrinmeyer** [comment] 2017-06-27 19:59
(thanks -- triple back ticks seem to be what I want.  I did not realize github was markdown by default)
anything else I can check? 
```
perrin@perrin:~$ glxinfo  |grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 12.0.6
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by hannorein** [comment] 2017-06-28 02:16
So this suggests your card should support version 4.30. I don't understand why your compiler then gives you an error message saying it only supports 1.10, 1.20, 1.30?

**Comment by jdong14** [comment] 2017-07-01 13:26
I had the same issue. It works on my Ubuntu after including

glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR,3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR,3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

on display.c.

**Comment by hannorein** [comment] 2017-07-01 14:47
Awesome. Do you want to send me a pull request with those lines?

**Comment by lordpeano** [comment] 2017-07-01 15:30
I am using Fedora 25 Spin Astronomy.  The equivalent to apt-get is dnf which does not support libglfw3.
Also, Fedora is moving for X11.  Presently on the KDE spin is the only one using Wayland. 

FWIW  I have not been able to get the GLFW to work.

**Comment by perrinmeyer** [comment] 2017-07-05 17:23
It now compiles and runs, but I'm not seeing anything.  It pops up a window that contains my desktop background, and then nothing happens... 
![reboundopenglissue](https://user-images.githubusercontent.com/647534/27876249-41bcf178-616b-11e7-97e5-6743ca242e9e.png)

I tried a couple of other examples and they compile, pop up a window, and then I dont see anything. 

am I just no waiting long enough for it to finish integrating?

**Comment by hannorein** [comment] 2017-07-05 18:06
Can you try the outer solar system one? Thanks.

**Comment by perrinmeyer** [comment] 2017-07-05 19:11
that seems to work!  I see planets(?) orbiting quickly. 
![reboundopengl2](https://user-images.githubusercontent.com/647534/27880776-09e37bc2-617b-11e7-8055-689ec7568404.png)

**Comment by hannorein** [comment] 2017-07-05 19:16
Phew. That's progress. I'll need to look into what is wrong with the other examples. I suspect it's related to the solid spheres (which is a different shader). In the meantime, you might see something on the other examples if you press the `s` button.

**Comment by perrinmeyer** [comment] 2017-07-05 19:39
thanks.
pressing the "s" button on the shearing_sheet example did not show anything... 

in the meantime i downloaded glfw source from github and compiled it (fun with cmake...), and I ran all the tests/examples, and they all seem to render ok, for what thats worth. GLFW seems like a nice library for opengl - not overly bloated... too bad that 20 years on the opengl infrastructure is not more stable, but i guess video/graphics cards are a fast moving target... 
perrin meyer
415 471 0136

**Comment by romainhry** [comment] 2018-03-26 11:58
Same problem as perrin for me, did you find a solution ?

**Comment by dtamayo** [comment] 2018-03-26 14:20
Which problem? What operating system are you running and can you check if your graphic card and drivers support OpenGL Shader Language (GLSL) version 3.30? Did you try any of the suggestions above?

**Comment by romainhry** [comment] 2018-03-26 19:07
When I force the version to 3.3 using : 
```
    QSurfaceFormat format;
    format.setVersion( 3, 3);
    format.setProfile( QSurfaceFormat::CoreProfile );
    QSurfaceFormat::setDefaultFormat(format);
```
it compiles but doesn't show anything (I do have the popup windows without any rendering inside).

If I use OpenGL 2.0 and version glsl 130 it works without forcing to 3.3. However I need OpenGL 3.3 + glsl 330 for my project.

I'm on Ubuntu 16.04 with Qt 5.10.
Find below my glxinfo -B return
![capture du 2018-03-26 20-59-44](https://user-images.githubusercontent.com/15669668/37927027-2f30225c-3139-11e8-9fc9-ad253c87caec.png)

**Comment by dtamayo** [comment] 2018-03-28 13:52
Hm, thanks for the info. Seems strange...Did you try to install glfw from source like Perrin did above to fix his problem?

**Comment by romainhry** [comment] 2018-03-28 22:19
Yes, but I don't think it fixes his problem, right ?

**Comment by hannorein** [comment] 2018-03-30 12:58
I simply don't have enough experience to help fixing this. Clearly this is due to some issue with different versions of OpenGL, GLFW and the specific graphic card used. I can't reproduce the issue on my end and I have no idea on how to fix it otherwise. Sorry for not being able to help more. If anyone finds a solution, please post it here or even better send us a pull request.

**Comment by perrinmeyer** [comment] 2018-03-30 18:15
Its been a while since I played with this, sorry I can't be more help. I think I built the opengl libs from source, and then I had to play with shared library paths (ldconfig or /etc/)  (I think I had to use the ubuntu package manager to remove some canned ubuntu packages), and then rebound was able to find the opengl libraries I built)
I might have a chance to look at what I did next week. 
perrin


    On Friday, March 30, 2018, 5:58:58 AM PDT, Hanno Rein <notifications@github.com> wrote:  
 
 
I simply don't have enough experience to help fixing this. Clearly this is due to some issue with different versions of OpenGL, GLFW and the specific graphic card used. I can't reproduce the issue on my end and I have no idea on how to fix it otherwise. Sorry for not being able to help more. If anyone finds a solution, please post it here or even better send us a pull request.

**Comment by dtamayo** [comment] 2018-11-20 22:37
So I'm getting the same behavior now in Mojave, opens up an empty window but nothing shows up (in solar system or others). If the glfwWindowHints are removed in display.c, it doesn't even open a screen. 

A dissatisfying fix is to move or resize the window to force it to refresh, at which point everything shows up and works. There are some fixes here

https://github.com/glfw/glfw/issues/1334

but they seem a bit convoluted. Maybe it's better to deal with moving the window until the next release of GLFW (though the last one was 2 years ago...)

**Comment by hannorein** [comment] 2018-11-20 22:55
This is frustrating...  If I understood it correctly, Apple announced to drop the OpenGL support in a future version completely. But I don't want to implement a platform specific solution. Any immediate fix for this issue aside, I'm not sure what long term approach we should be taking for the visualizations...

**Comment by jorgepiloto** [comment] 2020-11-29 19:34
Hi all,

I recently discovered this awesome package and wanted to give it a try. After running one of the examples (the outer solar system one), the following error was raised:

```bash
GLFW initialization failed
```

I am running on a Endeavour OS, an Arch Linux based distro, and though this problem might be solved by simply executing the following command to install the GLFW library:

```bash
sudo pacman -S glfw
```

However, even with this command, the animation was not shown and the same error was raised. Then, I noticed that there was another package under the name `glfw-x11` and decided to install this one:

```bash
sudo pacman -S glfw-x11
```

With this particular package, no error was raised and the animation and its controls worked as expected. I am not so familiar with OpenGL and associated libraries but thought this information might be useful for other people and developers.

**Comment by hannorein** [comment] 2020-11-29 20:17
Thanks for sharing. This might indeed be useful for other. 

It looks like every operating system has a completely different way to handle GLFW and OpenGL. In the long run I need to move the real time visualization to some other framework. But it's hard to find one which works reliably on most operating systems...

**Comment by hannorein** [comment] 2021-01-02 22:59
I'll close this issue for now. If anyone else has issues with the glfw libraries, feel free to open a new issue.

**Closed by hannorein** 2021-01-02 22:59 UTC
